version: '3.8'

services:
  nextjs:
    container_name: next-landing-vpn-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4400:4400"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["npm", "start"]

